const questions = [
  // ===== SECTION 1: 基本情報 (1-15) =====
  { id: 1, section: "基本情報", q: "会社名（正式名称）", type: "text", placeholder: "例：和泉出版印刷株式会社" },
  { id: 2, section: "基本情報", q: "会社名（フリガナ）", type: "text", placeholder: "例：イズミシュッパンインサツ" },
  { id: 3, section: "基本情報", q: "代表者名", type: "text", placeholder: "例：山田 太郎" },
  { id: 4, section: "基本情報", q: "設立年", type: "text", placeholder: "例：1975年" },
  { id: 5, section: "基本情報", q: "資本金", type: "text", placeholder: "例：1,000万円" },
  { id: 6, section: "基本情報", q: "従業員数", type: "text", placeholder: "例：25名" },
  { id: 7, section: "基本情報", q: "本社所在地（郵便番号）", type: "text", placeholder: "例：594-0000" },
  { id: 8, section: "基本情報", q: "本社所在地（住所）", type: "text", placeholder: "例：大阪府和泉市○○町1-2-3" },
  { id: 9, section: "基本情報", q: "電話番号", type: "text", placeholder: "例：0725-00-0000" },
  { id: 10, section: "基本情報", q: "FAX番号", type: "text", placeholder: "例：0725-00-0001" },
  { id: 11, section: "基本情報", q: "メールアドレス（公開用）", type: "text", placeholder: "例：info@izumi-print.co.jp" },
  { id: 12, section: "基本情報", q: "現在のWebサイトURL（あれば）", type: "text", placeholder: "例：https://www.izumi-print.co.jp" },
  { id: 13, section: "基本情報", q: "営業時間", type: "text", placeholder: "例：平日 9:00〜18:00" },
  { id: 14, section: "基本情報", q: "定休日", type: "text", placeholder: "例：土日祝" },
  { id: 15, section: "基本情報", q: "アクセス方法（最寄り駅・バス停など）", type: "textarea", placeholder: "例：JR阪和線 和泉府中駅から徒歩10分" },

  // ===== SECTION 2: 事業内容 (16-40) =====
  { id: 16, section: "事業内容", q: "主な事業内容を教えてください", type: "textarea", placeholder: "例：商業印刷、出版印刷、デザイン制作" },
  { id: 17, section: "事業内容", q: "主力サービス・商品は何ですか？", type: "textarea", placeholder: "" },
  { id: 18, section: "事業内容", q: "オフセット印刷は対応していますか？", type: "select", options: ["対応している", "対応していない", "検討中"] },
  { id: 19, section: "事業内容", q: "デジタル印刷（オンデマンド）は対応していますか？", type: "select", options: ["対応している", "対応していない", "検討中"] },
  { id: 20, section: "事業内容", q: "大判印刷（ポスター・看板等）は対応していますか？", type: "select", options: ["対応している", "対応していない", "検討中"] },
  { id: 21, section: "事業内容", q: "製本・加工は対応していますか？", type: "select", options: ["対応している", "対応していない", "外注で対応"] },
  { id: 22, section: "事業内容", q: "デザイン制作は対応していますか？", type: "select", options: ["対応している", "対応していない", "外注で対応"] },
  { id: 23, section: "事業内容", q: "DTP・データ作成は対応していますか？", type: "select", options: ["対応している", "対応していない", "外注で対応"] },
  { id: 24, section: "事業内容", q: "名刺印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 25, section: "事業内容", q: "チラシ・フライヤー印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 26, section: "事業内容", q: "パンフレット・カタログ印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 27, section: "事業内容", q: "冊子・書籍印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 28, section: "事業内容", q: "封筒・はがき印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 29, section: "事業内容", q: "シール・ラベル印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 30, section: "事業内容", q: "ノベルティ・グッズ印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 31, section: "事業内容", q: "梱包・パッケージ印刷は対応していますか？", type: "select", options: ["対応している", "対応していない"] },
  { id: 32, section: "事業内容", q: "特殊印刷（箔押し・エンボス等）は対応していますか？", type: "select", options: ["対応している", "対応していない", "一部対応"] },
  { id: 33, section: "事業内容", q: "その他対応している印刷物があれば教えてください", type: "textarea", placeholder: "" },
  { id: 34, section: "事業内容", q: "小ロット（少部数）の対応は可能ですか？", type: "select", options: ["可能", "不可", "応相談"] },
  { id: 35, section: "事業内容", q: "最短納期はどのくらいですか？", type: "text", placeholder: "例：データ入稿後3営業日" },
  { id: 36, section: "事業内容", q: "配送・納品方法を教えてください", type: "textarea", placeholder: "例：宅配便、自社便、店頭引取り" },
  { id: 37, section: "事業内容", q: "対応エリアを教えてください", type: "text", placeholder: "例：大阪府内、全国対応" },
  { id: 38, section: "事業内容", q: "環境への取り組みはありますか？", type: "textarea", placeholder: "例：FSC認証紙使用、ベジタブルインキ使用" },
  { id: 39, section: "事業内容", q: "取得している認証・資格はありますか？", type: "textarea", placeholder: "例：ISO9001、プライバシーマーク" },
  { id: 40, section: "事業内容", q: "他社と比べた強み・特徴は何ですか？", type: "textarea", placeholder: "" },

  // ===== SECTION 3: ターゲット・顧客 (41-55) =====
  { id: 41, section: "ターゲット・顧客", q: "主なターゲット顧客は？", type: "multi", options: ["法人（大企業）", "法人（中小企業）", "個人事業主", "個人", "官公庁・自治体", "教育機関", "医療機関", "その他"] },
  { id: 42, section: "ターゲット・顧客", q: "特に注力したい業界はありますか？", type: "textarea", placeholder: "例：飲食店、不動産、学校" },
  { id: 43, section: "ターゲット・顧客", q: "既存顧客の業界・業種を教えてください", type: "textarea", placeholder: "" },
  { id: 44, section: "ターゲット・顧客", q: "新規顧客の獲得を重視していますか？", type: "select", options: ["非常に重視", "やや重視", "現状維持でよい"] },
  { id: 45, section: "ターゲット・顧客", q: "HPから問い合わせを増やしたいですか？", type: "select", options: ["はい", "いいえ", "わからない"] },
  { id: 46, section: "ターゲット・顧客", q: "見込み顧客が検索しそうなキーワードは？", type: "textarea", placeholder: "例：和泉市 印刷、大阪 名刺印刷" },
  { id: 47, section: "ターゲット・顧客", q: "顧客からよく聞かれる質問は？", type: "textarea", placeholder: "" },
  { id: 48, section: "ターゲット・顧客", q: "顧客が御社を選ぶ理由は何だと思いますか？", type: "textarea", placeholder: "" },
  { id: 49, section: "ターゲット・顧客", q: "リピート率はどのくらいですか？", type: "text", placeholder: "例：約80%" },
  { id: 50, section: "ターゲット・顧客", q: "取引先・お客様の声（推薦文）を掲載できますか？", type: "select", options: ["掲載可能", "確認が必要", "掲載不可"] },
  { id: 51, section: "ターゲット・顧客", q: "事例・実績の掲載は可能ですか？", type: "select", options: ["掲載可能", "一部可能", "掲載不可"] },
  { id: 52, section: "ターゲット・顧客", q: "価格表の掲載を希望しますか？", type: "select", options: ["掲載する", "参考価格のみ", "掲載しない（要見積もり）"] },
  { id: 53, section: "ターゲット・顧客", q: "オンラインでの見積もり機能は必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 54, section: "ターゲット・顧客", q: "オンラインでのデータ入稿機能は必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 55, section: "ターゲット・顧客", q: "EC（オンライン注文）機能は必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },

  // ===== SECTION 4: 現在のHP・Web状況 (56-75) =====
  { id: 56, section: "現在のHP・Web状況", q: "現在ホームページはありますか？", type: "select", options: ["ある", "ない", "以前あったが閉鎖した"] },
  { id: 57, section: "現在のHP・Web状況", q: "現在のHPの不満点は？", type: "textarea", placeholder: "" },
  { id: 58, section: "現在のHP・Web状況", q: "現在のHPの良い点（残したい点）は？", type: "textarea", placeholder: "" },
  { id: 59, section: "現在のHP・Web状況", q: "現在のHPの月間アクセス数は？", type: "text", placeholder: "例：月300PV程度、わからない" },
  { id: 60, section: "現在のHP・Web状況", q: "現在のHPからの問い合わせ数は？", type: "text", placeholder: "例：月2〜3件程度" },
  { id: 61, section: "現在のHP・Web状況", q: "独自ドメインを持っていますか？", type: "select", options: ["持っている", "持っていない", "わからない"] },
  { id: 62, section: "現在のHP・Web状況", q: "ドメイン名を教えてください（あれば）", type: "text", placeholder: "例：izumi-print.co.jp" },
  { id: 63, section: "現在のHP・Web状況", q: "レンタルサーバーは契約していますか？", type: "select", options: ["契約している", "していない", "わからない"] },
  { id: 64, section: "現在のHP・Web状況", q: "サーバー会社名（わかれば）", type: "text", placeholder: "例：さくらインターネット、Xserver" },
  { id: 65, section: "現在のHP・Web状況", q: "Google Analyticsは導入していますか？", type: "select", options: ["導入済み", "未導入", "わからない"] },
  { id: 66, section: "現在のHP・Web状況", q: "Google Search Consoleは導入していますか？", type: "select", options: ["導入済み", "未導入", "わからない"] },
  { id: 67, section: "現在のHP・Web状況", q: "Googleマイビジネスは登録していますか？", type: "select", options: ["登録済み", "未登録", "わからない"] },
  { id: 68, section: "現在のHP・Web状況", q: "SNSアカウントはありますか？（Instagram）", type: "text", placeholder: "アカウント名またはURL" },
  { id: 69, section: "現在のHP・Web状況", q: "SNSアカウントはありますか？（Facebook）", type: "text", placeholder: "アカウント名またはURL" },
  { id: 70, section: "現在のHP・Web状況", q: "SNSアカウントはありますか？（X / Twitter）", type: "text", placeholder: "アカウント名またはURL" },
  { id: 71, section: "現在のHP・Web状況", q: "SNSアカウントはありますか？（LINE公式）", type: "text", placeholder: "アカウント名またはURL" },
  { id: 72, section: "現在のHP・Web状況", q: "SNSアカウントはありますか？（YouTube）", type: "text", placeholder: "アカウント名またはURL" },
  { id: 73, section: "現在のHP・Web状況", q: "その他のSNS・ポータルサイトがあれば", type: "textarea", placeholder: "" },
  { id: 74, section: "現在のHP・Web状況", q: "Web広告（リスティング広告等）は出稿していますか？", type: "select", options: ["出稿している", "過去に出稿", "出稿していない"] },
  { id: 75, section: "現在のHP・Web状況", q: "SEO対策は行っていますか？", type: "select", options: ["行っている", "過去に行った", "行っていない", "わからない"] },

  // ===== SECTION 5: 新HPの目的・ゴール (76-95) =====
  { id: 76, section: "新HPの目的・ゴール", q: "新しいHPの一番の目的は？", type: "multi", options: ["会社の信頼性向上", "新規顧客の獲得", "問い合わせ増加", "採用強化", "ブランディング", "既存顧客への情報発信", "ECサイト構築", "その他"] },
  { id: 77, section: "新HPの目的・ゴール", q: "HPで最も伝えたいメッセージは？", type: "textarea", placeholder: "" },
  { id: 78, section: "新HPの目的・ゴール", q: "HPを見た人にどんな行動をしてほしいですか？", type: "multi", options: ["電話をかける", "メールで問い合わせ", "フォームから見積依頼", "来社する", "資料請求", "オンライン注文", "その他"] },
  { id: 79, section: "新HPの目的・ゴール", q: "競合他社のHPで参考にしたいサイトは？（URL）", type: "textarea", placeholder: "URLを複数記載OK" },
  { id: 80, section: "新HPの目的・ゴール", q: "参考にしたいサイトのどこが良いと思いますか？", type: "textarea", placeholder: "" },
  { id: 81, section: "新HPの目的・ゴール", q: "逆に「こうはしたくない」というサイトはありますか？", type: "textarea", placeholder: "" },
  { id: 82, section: "新HPの目的・ゴール", q: "HPのリニューアル（新規作成）の理由は？", type: "textarea", placeholder: "" },
  { id: 83, section: "新HPの目的・ゴール", q: "ターゲットが「ここに頼みたい」と思うポイントは何だと思いますか？", type: "textarea", placeholder: "" },
  { id: 84, section: "新HPの目的・ゴール", q: "会社のキャッチコピー・スローガンはありますか？", type: "text", placeholder: "例：品質と速さで、あなたの想いを形に。" },
  { id: 85, section: "新HPの目的・ゴール", q: "企業理念・ミッションはありますか？", type: "textarea", placeholder: "" },
  { id: 86, section: "新HPの目的・ゴール", q: "HPの公開希望時期は？", type: "text", placeholder: "例：2026年6月末" },
  { id: 87, section: "新HPの目的・ゴール", q: "予算感を教えてください", type: "select", options: ["〜30万円", "30〜50万円", "50〜100万円", "100万円以上", "要相談"] },
  { id: 88, section: "新HPの目的・ゴール", q: "月額の運用・保守費用の予算は？", type: "select", options: ["〜5,000円/月", "5,000〜10,000円/月", "10,000〜30,000円/月", "30,000円以上/月", "要相談"] },
  { id: 89, section: "新HPの目的・ゴール", q: "今後HPを自社で更新したいですか？", type: "select", options: ["自社で更新したい", "更新は委託したい", "どちらでもよい"] },
  { id: 90, section: "新HPの目的・ゴール", q: "ブログ・お知らせ機能は必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 91, section: "新HPの目的・ゴール", q: "多言語対応は必要ですか？", type: "select", options: ["不要", "英語のみ", "英語＋中国語", "その他"] },
  { id: 92, section: "新HPの目的・ゴール", q: "採用ページは必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 93, section: "新HPの目的・ゴール", q: "会員機能・ログイン機能は必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 94, section: "新HPの目的・ゴール", q: "チャット機能は必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 95, section: "新HPの目的・ゴール", q: "その他、HPに必要な機能があれば", type: "textarea", placeholder: "" },

  // ===== SECTION 6: デザイン・ブランド (96-120) =====
  { id: 96, section: "デザイン・ブランド", q: "会社のロゴデータはありますか？", type: "select", options: ["ある（AI/EPS形式）", "ある（PNG/JPG形式）", "ない", "新しく作りたい"] },
  { id: 97, section: "デザイン・ブランド", q: "コーポレートカラーはありますか？", type: "text", placeholder: "例：紺色と白" },
  { id: 98, section: "デザイン・ブランド", q: "HPで使いたい色のイメージは？", type: "multi", options: ["信頼感のある青系", "温かみのある暖色系", "シンプルなモノトーン", "高級感のある黒・金系", "爽やかな緑系", "おまかせ", "その他"] },
  { id: 99, section: "デザイン・ブランド", q: "HPの雰囲気はどんなイメージですか？", type: "multi", options: ["信頼・安心感", "先進的・モダン", "親しみやすい・カジュアル", "高級・プレミアム", "伝統的・格式", "シンプル・ミニマル", "おまかせ"] },
  { id: 100, section: "デザイン・ブランド", q: "写真素材はありますか？（社屋外観）", type: "select", options: ["ある", "ない（撮影したい）", "ない（素材でOK）"] },
  { id: 101, section: "デザイン・ブランド", q: "写真素材はありますか？（社内・工場）", type: "select", options: ["ある", "ない（撮影したい）", "ない（素材でOK）"] },
  { id: 102, section: "デザイン・ブランド", q: "写真素材はありますか？（印刷機・設備）", type: "select", options: ["ある", "ない（撮影したい）", "ない（素材でOK）"] },
  { id: 103, section: "デザイン・ブランド", q: "写真素材はありますか？（制作実績・作品）", type: "select", options: ["ある", "ない（撮影したい）", "ない（素材でOK）"] },
  { id: 104, section: "デザイン・ブランド", q: "写真素材はありますか？（スタッフ）", type: "select", options: ["ある", "ない（撮影したい）", "ない（素材でOK）", "顔出しNG"] },
  { id: 105, section: "デザイン・ブランド", q: "写真撮影を依頼したいですか？", type: "select", options: ["依頼したい", "自社で用意する", "素材写真でOK"] },
  { id: 106, section: "デザイン・ブランド", q: "動画コンテンツは必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 107, section: "デザイン・ブランド", q: "イラスト・アイコンのテイストは？", type: "select", options: ["シンプル・フラット", "手描き風", "リアル", "不要", "おまかせ"] },
  { id: 108, section: "デザイン・ブランド", q: "フォントのイメージは？", type: "select", options: ["ゴシック系（モダン）", "明朝系（上品）", "丸ゴシック（親しみ）", "おまかせ"] },
  { id: 109, section: "デザイン・ブランド", q: "アニメーション・動きのあるデザインは好きですか？", type: "select", options: ["あった方がよい", "控えめに", "不要", "おまかせ"] },
  { id: 110, section: "デザイン・ブランド", q: "ファーストビュー（最初に見える部分）に何を置きたいですか？", type: "textarea", placeholder: "例：キャッチコピーと社屋の写真" },
  { id: 111, section: "デザイン・ブランド", q: "会社の歴史・沿革を掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 112, section: "デザイン・ブランド", q: "社長メッセージ・挨拶を掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 113, section: "デザイン・ブランド", q: "スタッフ紹介を掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 114, section: "デザイン・ブランド", q: "設備紹介を掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 115, section: "デザイン・ブランド", q: "工程・ワークフロー紹介を掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 116, section: "デザイン・ブランド", q: "品質管理への取り組みを掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 117, section: "デザイン・ブランド", q: "お客様の声・レビューを掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "集める予定"] },
  { id: 118, section: "デザイン・ブランド", q: "よくある質問（FAQ）ページは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 119, section: "デザイン・ブランド", q: "プライバシーポリシーは既にありますか？", type: "select", options: ["ある", "ない（作成してほしい）"] },
  { id: 120, section: "デザイン・ブランド", q: "名刺やパンフレット等、既存の印刷物のデザインデータはありますか？", type: "select", options: ["ある", "ない"] },

  // ===== SECTION 7: ページ構成 (121-145) =====
  { id: 121, section: "ページ構成", q: "トップページ（ホーム）は必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 122, section: "ページ構成", q: "会社概要ページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 123, section: "ページ構成", q: "事業内容・サービス紹介ページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 124, section: "ページ構成", q: "サービスごとに個別ページが必要ですか？", type: "select", options: ["個別ページが必要", "1ページにまとめてOK", "検討中"] },
  { id: 125, section: "ページ構成", q: "制作実績・ギャラリーページは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 126, section: "ページ構成", q: "料金表ページは必要ですか？", type: "select", options: ["必要", "不要", "参考価格のみ掲載"] },
  { id: 127, section: "ページ構成", q: "ご利用の流れ（注文〜納品）ページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 128, section: "ページ構成", q: "お問い合わせページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 129, section: "ページ構成", q: "お見積もり依頼ページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 130, section: "ページ構成", q: "データ入稿ガイドページは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 131, section: "ページ構成", q: "テンプレートダウンロードページは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 132, section: "ページ構成", q: "アクセス・地図ページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 133, section: "ページ構成", q: "お知らせ・ニュースページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 134, section: "ページ構成", q: "ブログ・コラムページは必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 135, section: "ページ構成", q: "採用情報ページは必要ですか？", type: "select", options: ["必要", "不要", "将来的に検討"] },
  { id: 136, section: "ページ構成", q: "代表挨拶ページは必要ですか？", type: "select", options: ["必要", "会社概要に含める", "不要"] },
  { id: 137, section: "ページ構成", q: "沿革ページは必要ですか？", type: "select", options: ["必要", "会社概要に含める", "不要"] },
  { id: 138, section: "ページ構成", q: "設備紹介ページは必要ですか？", type: "select", options: ["必要", "事業内容に含める", "不要"] },
  { id: 139, section: "ページ構成", q: "環境への取り組みページは必要ですか？", type: "select", options: ["必要", "会社概要に含める", "不要"] },
  { id: 140, section: "ページ構成", q: "お客様の声ページは必要ですか？", type: "select", options: ["必要", "トップページに含める", "不要"] },
  { id: 141, section: "ページ構成", q: "FAQページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 142, section: "ページ構成", q: "サイトマップページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 143, section: "ページ構成", q: "プライバシーポリシーページは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 144, section: "ページ構成", q: "その他、必要なページがあれば教えてください", type: "textarea", placeholder: "" },
  { id: 145, section: "ページ構成", q: "合計何ページくらいを想定していますか？", type: "select", options: ["5ページ以下", "5〜10ページ", "10〜20ページ", "20ページ以上", "おまかせ"] },

  // ===== SECTION 8: コンテンツ・原稿 (146-165) =====
  { id: 146, section: "コンテンツ・原稿", q: "各ページの原稿（文章）は誰が用意しますか？", type: "select", options: ["自社で用意する", "制作会社に依頼したい", "一緒に作りたい"] },
  { id: 147, section: "コンテンツ・原稿", q: "会社紹介の文章は既にありますか？", type: "select", options: ["ある", "ない（作成してほしい）", "既存の文章を修正したい"] },
  { id: 148, section: "コンテンツ・原稿", q: "サービス説明の文章は既にありますか？", type: "select", options: ["ある", "ない（作成してほしい）", "既存の文章を修正したい"] },
  { id: 149, section: "コンテンツ・原稿", q: "HP用のキャッチコピー案があればお書きください（Q84と異なるものでもOK）", type: "text", placeholder: "例：あなたの「伝えたい」を、カタチにする印刷会社" },
  { id: 150, section: "コンテンツ・原稿", q: "掲載したい実績の数はどのくらいですか？", type: "text", placeholder: "例：10〜20件" },
  { id: 151, section: "コンテンツ・原稿", q: "実績の写真は用意できますか？", type: "select", options: ["用意できる", "一部のみ", "用意できない"] },
  { id: 152, section: "コンテンツ・原稿", q: "印刷の豆知識・コラムネタはありますか？", type: "select", options: ["ある", "ない", "一緒に考えたい"] },
  { id: 153, section: "コンテンツ・原稿", q: "社長のプロフィール・経歴を掲載しますか？", type: "select", options: ["掲載する", "掲載しない"] },
  { id: 154, section: "コンテンツ・原稿", q: "主要な印刷設備の名称・スペックを掲載しますか？", type: "select", options: ["掲載する", "掲載しない", "検討中"] },
  { id: 155, section: "コンテンツ・原稿", q: "取引先企業名の掲載は可能ですか？", type: "select", options: ["可能", "一部のみ", "不可"] },
  { id: 156, section: "コンテンツ・原稿", q: "入稿データの対応形式を教えてください", type: "textarea", placeholder: "例：Illustrator、Photoshop、PDF、Word" },
  { id: 157, section: "コンテンツ・原稿", q: "注文から納品までの流れを教えてください", type: "textarea", placeholder: "例：①お問い合わせ→②お見積り→③データ入稿→④印刷→⑤納品" },
  { id: 158, section: "コンテンツ・原稿", q: "支払い方法を教えてください", type: "textarea", placeholder: "例：銀行振込、請求書払い" },
  { id: 159, section: "コンテンツ・原稿", q: "送料について教えてください", type: "text", placeholder: "例：5,000円以上送料無料、実費" },
  { id: 160, section: "コンテンツ・原稿", q: "返品・キャンセルポリシーを教えてください", type: "textarea", placeholder: "" },
  { id: 161, section: "コンテンツ・原稿", q: "校正の回数・方法を教えてください", type: "text", placeholder: "例：初校・再校の2回、PDFにて" },
  { id: 162, section: "コンテンツ・原稿", q: "色校正は対応していますか？", type: "select", options: ["対応（有料）", "対応（無料）", "非対応"] },
  { id: 163, section: "コンテンツ・原稿", q: "サンプル・見本の提供は可能ですか？", type: "select", options: ["可能", "有料で可能", "不可"] },
  { id: 164, section: "コンテンツ・原稿", q: "紙の種類・厚さの相談はできますか？", type: "select", options: ["相談可能", "おまかせが多い"] },
  { id: 165, section: "コンテンツ・原稿", q: "その他、HPに掲載したい情報があれば", type: "textarea", placeholder: "" },

  // ===== SECTION 9: 技術・機能要件 (166-185) =====
  { id: 166, section: "技術・機能要件", q: "スマートフォン対応（レスポンシブ）は必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 167, section: "技術・機能要件", q: "お問い合わせフォームに必要な項目は？", type: "multi", options: ["会社名", "お名前", "メールアドレス", "電話番号", "住所", "お問い合わせ内容", "印刷物の種類", "数量", "希望納期", "添付ファイル"] },
  { id: 168, section: "技術・機能要件", q: "見積もりフォームに必要な項目は？", type: "textarea", placeholder: "例：印刷物の種類、サイズ、部数、紙質、色数、加工" },
  { id: 169, section: "技術・機能要件", q: "SSL（https）対応は必要ですか？", type: "select", options: ["必要", "不要", "わからない"] },
  { id: 170, section: "技術・機能要件", q: "CMSの希望はありますか？", type: "select", options: ["WordPress", "特にこだわりなし", "静的サイトでOK", "わからない"] },
  { id: 171, section: "技術・機能要件", q: "お知らせの更新頻度はどのくらいですか？", type: "select", options: ["週1回以上", "月1〜2回", "数ヶ月に1回", "ほとんど更新しない"] },
  { id: 172, section: "技術・機能要件", q: "メールフォームの送信先アドレスは？", type: "text", placeholder: "例：info@izumi-print.co.jp" },
  { id: 173, section: "技術・機能要件", q: "自動返信メールは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 174, section: "技術・機能要件", q: "Googleマップの埋め込みは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 175, section: "技術・機能要件", q: "SNS連携（シェアボタン等）は必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 176, section: "技術・機能要件", q: "OGP設定（SNSシェア時の画像・説明文）は必要ですか？", type: "select", options: ["必要", "不要", "わからない"] },
  { id: 177, section: "技術・機能要件", q: "ファビコン（ブラウザタブのアイコン）は用意できますか？", type: "select", options: ["用意できる", "作成してほしい", "わからない"] },
  { id: 178, section: "技術・機能要件", q: "印刷物のPDFダウンロード機能は必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 179, section: "技術・機能要件", q: "画像ギャラリー・スライドショーは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 180, section: "技術・機能要件", q: "ページ内検索機能は必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 181, section: "技術・機能要件", q: "アクセシビリティ対応は必要ですか？", type: "select", options: ["必要", "可能な範囲で", "不要"] },
  { id: 182, section: "技術・機能要件", q: "ページ表示速度の最適化は重視しますか？", type: "select", options: ["重視する", "普通でよい"] },
  { id: 183, section: "技術・機能要件", q: "Cookie同意バナーは必要ですか？", type: "select", options: ["必要", "不要", "わからない"] },
  { id: 184, section: "技術・機能要件", q: "既存システムとの連携が必要なものはありますか？", type: "textarea", placeholder: "例：基幹システム、受注管理システム" },
  { id: 185, section: "技術・機能要件", q: "外部サービスとの連携が必要なものはありますか？", type: "textarea", placeholder: "例：MailChimp、Stripe、PayPal" },

  // ===== SECTION 10: 運用・保守 (186-200) =====
  { id: 186, section: "運用・保守", q: "HP公開後の更新は誰が行いますか？", type: "select", options: ["自社の担当者", "制作会社に委託", "未定"] },
  { id: 187, section: "運用・保守", q: "更新担当者のWeb知識レベルは？", type: "select", options: ["詳しい", "基本的な操作はできる", "ほぼ初心者", "未定"] },
  { id: 188, section: "運用・保守", q: "更新マニュアルは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 189, section: "運用・保守", q: "操作レクチャーは必要ですか？", type: "select", options: ["必要", "不要"] },
  { id: 190, section: "運用・保守", q: "サーバー・ドメインの管理は誰が行いますか？", type: "select", options: ["自社", "制作会社に委託", "わからない"] },
  { id: 191, section: "運用・保守", q: "定期的なバックアップは必要ですか？", type: "select", options: ["必要", "不要", "わからない"] },
  { id: 192, section: "運用・保守", q: "セキュリティ対策の要件はありますか？", type: "textarea", placeholder: "" },
  { id: 193, section: "運用・保守", q: "アクセス解析レポートは必要ですか？", type: "select", options: ["必要（月次）", "必要（四半期）", "不要"] },
  { id: 194, section: "運用・保守", q: "将来的にページを追加する予定はありますか？", type: "select", options: ["ある", "ない", "わからない"] },
  { id: 195, section: "運用・保守", q: "将来的にECサイト化する予定はありますか？", type: "select", options: ["ある", "ない", "わからない"] },
  { id: 196, section: "運用・保守", q: "SEO対策の継続的なサポートは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 197, section: "運用・保守", q: "Web広告の運用サポートは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 198, section: "運用・保守", q: "SNS運用のサポートは必要ですか？", type: "select", options: ["必要", "不要", "検討中"] },
  { id: 199, section: "運用・保守", q: "HPに関するご担当者のお名前・連絡先", type: "textarea", placeholder: "お名前、電話番号、メールアドレス" },
  { id: 200, section: "運用・保守", q: "その他、ご要望・ご質問があればご自由にお書きください", type: "textarea", placeholder: "" },
];

export default questions;

export const sections = [
  "基本情報",
  "事業内容",
  "ターゲット・顧客",
  "現在のHP・Web状況",
  "新HPの目的・ゴール",
  "デザイン・ブランド",
  "ページ構成",
  "コンテンツ・原稿",
  "技術・機能要件",
  "運用・保守",
];
